import {
  LayoutGrid,
  User,
  UploadCloud,
  MessageCircle,
  Calendar,
  Music2,
  Video,
  Mail,
  Palette,
  Monitor,
  Timer,
  Map,
} from "lucide-react"; // import ไอคอนที่ต้องการ

export const reviews = [
  {
    name: "ธีมการ์ดหลากหลาย",
    description: "เลือกธีมการ์ดแต่งงานสไตล์ที่ชอบ",
    time: "1m ago",
    icon: LayoutGrid,
    color: "#F7DAE1",
    link: "/feature/theme",
  },
  {
    name: "แกลเลอรี่รูปภาพ",
    description: "อัพโหลดรูปถ่ายคู่บ่าวสาวได้",
    time: "1m ago",
    icon: UploadCloud,
    color: "#F7E2D5",
    link: "/feature/gallery",
  },
  {
    name: "ระบบ RSVP",
    description: "แขกยืนยันการเข้าร่วมงานผ่านฟอร์ม",
    time: "1m ago",
    icon: MessageCircle,
    color: "#F7EFD5",
    link: "/feature/rsvp",
  },
  {
    name: "Countdown",
    description: "นับถอยหลังวันแต่งงานแบบเรียลไทม์",
    time: "1m ago",
    icon: Timer,
    color: "#ECF7D5",
    link: "/feature/countdown",
  },
  {
    name: "แผนที่",
    description: "แผนที่ Google Maps",
    time: "1m ago",
    icon: Map,
    color: "#D5F7E0",
    link: "/feature/map",
  },
  {
    name: "Guest Book",
    description: "แขกเขียนคำอวยพรให้คู่บ่าวสาว",
    time: "1m ago",
    icon: User,
    color: "#D5F7F7",
    link: "/feature/guestbook",
  },
  {
    name: "Dress Code",
    description: "แจ้งธีมงาน การแต่งกาย",
    time: "1m ago",
    icon: Palette,
    color: "#D5E8F7",
    link: "/feature/dress-code",
  },
  {
    name: "รองรับทุกหน้าจอ",
    description: "เปิดดูได้สวยทั้งมือถือและคอมพิวเตอร์",
    time: "1m ago",
    icon: Monitor,
    color: "#DAD5F7",
    link: "/feature/responsive",
  },
  {
    name: "กำหนดการงาน",
    description: "แจ้งกำหนดการของงานแต่งงาน",
    time: "1m ago",
    icon: Calendar,
    color: "#F7D5ED",
    link: "/feature/timeline",
  },
  {
    name: "Contact Info",
    description: "ใส่ช่องทางติดต่อฝ่ายเจ้าบ่าว-เจ้าสาว",
    time: "1m ago",
    icon: Mail,
    color: "#F7D5DE",
    link: "/feature/contact",
  },
  {
    name: "เพลงประกอบ",
    description: "เปิดอัตโนมัติเมื่อเข้าชมการ์ด",
    time: "1m ago",
    icon: Music2,
    color: "#F7E1D5",
    link: "/feature/song",
  },
  {
    name: "วิดีโอ",
    description: "ฝังวิดีโอ Pre-wedding จาก YouTube ",
    time: "1m ago",
    icon: Video,
    color: "#F7F5D5",
    link: "/feature/video",
  },
];

export const THEME_RECOMMENDATIONS = [
  {
    index: 1,
    name: "🌿 Olive Garden",
    image: "/images/theme/olive-garden.png",
    desc: "เขียวมะกอก + ฟอนต์ลายมือ แนวธรรมชาติ Outdoor เหมาะกับ คนที่ชอบแนวสวน ธรรมชาติ",
    link: "/example/basic/olive-garden",
  },
  {
    index: 2,
    name: "🌿 Olive Garden",
    image: "/images/theme/olive-garden.png",
    desc: "เขียวมะกอก + ฟอนต์ลายมือ แนวธรรมชาติ Outdoor เหมาะกับ คนที่ชอบแนวสวน ธรรมชาติ",
    link: "/example/basic/olive-garden",
  },
];
